### ISSUE TITLE
"API of the renderer is broken"

### ISSUE THREAD

**Issue by GedeonGrays** [GTNewHorizons/CodeChickenLib#15]
Hello o/

I apologize for linking to another issues-tracker, but this will make it easier to explain the nature of the current issue.

The problem with RPLE: https://github.com/GTMEGA/RPLE/issues/8

**Comment by Caedis** [comment]
~~False changed the CCL API in their fork and then used it in RPLE~~

Disregard

**Comment by mitchej123** [comment]
LIkely fixed by https://github.com/GTNewHorizons/CodeChickenLib/pull/16

**Comment by GedeonGrays** [comment]
Looks like the problem is not solved. 
Line 53 of the crash report and some other lines have changed a bit, otherwise the crash is the same.
[crash-2024-07-01_22.31.08-client.txt](https://github.com/user-attachments/files/16058334/crash-2024-07-01_22.31.08-client.txt)

**Comment by mitchej123** [comment]
The latest crash is a bug on RPLE's side.  

```
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method brightness in mixins.rple.json:client.codechickenlib.CCRenderStateMixin from mod rple was not located in the target class codechicken.lib.render.CCRenderState. Using refmap mixins.rple.refmap.json
```

[This line](https://github.com/GTMEGA/RPLE/blob/master/src/main/java/com/falsepattern/rple/internal/mixin/mixins/client/codechickenlib/CCRenderStateMixin.java#L43-L46) - doesn't exist in upstream CCL and was added to the public API by the gtmega fork [here](https://github.com/GTMEGA/CodeChickenLib/commit/ea1e68bf1c643446239544f91a495fb1758ace12#diff-77d74e654f26b3d6f3833ea8a8dd7c9c724ab7fd8f7cdf22fb1b043d491fc813R489-R491).
